vertotrade/verto.ui

.github/workflows/format.yml
.github/workflows/lint.yml

DEV-515 Fix build

---

apps/web/src/config/constants/pools.tsx
apps/web/src/hooks/useGetBlockCountdown.ts
apps/web/src/hooks/useNftClaimStatusCheck.tsx
apps/web/src/hooks/useSubgraphHealth.ts
apps/web/src/hooks/useTokenBalance.ts
apps/web/src/state/pools/index.ts
apps/web/src/utils/providers.ts
apps/web/src/views/FarmAuction/helpers.tsx
apps/web/src/views/Migration/hook/V1/Pool/useFetchIfoPool.ts
apps/web/src/views/Pools/components/PoolStatsInfo.tsx

Configure rebus pools
Staking seems to be working fine, but add/remove and harvest actions seem to be throwing an error `InvalidArgument desc = rpc error: code = InvalidArgument desc = both gasPrice and (maxFeePerGas or maxPriorityFeePerGas) specified: invalid`

DEV-515 Configure rebus pools

---

packages/uikit/src/widgets/Pool/PoolTabButtons.tsx

Feat(Dev-516): force alignment

---

apps/web/src/components/AddToWallet/AddToWalletButton.tsx
apps/web/src/views/Pools/components/PoolStatsInfo.tsx
apps/web/src/views/Swap/components/HotTokenList/SwapTokenTable.tsx

Fix token images when adding to wallet

Fix token images when adding to wallet

---

apps/web/src/components/Menu/UserMenu/WalletInfo.tsx
apps/web/src/config/wallet.ts

DEV-518 Remove not working wallets

---

apps/web/src/components/App/Transactions/TransactionsModal.tsx
apps/web/src/components/Menu/GlobalSettings/ExpertModal.tsx
apps/web/src/components/Menu/UserMenu/WalletModal.tsx
apps/web/src/components/TransactionConfirmationModal/index.tsx
apps/web/src/views/Swap/components/ConfirmSwapModalContainer.tsx
packages/ui/tokens/colors.ts
packages/uikit/src/components/RoiCalculatorModal/RoiCalculatorModal.tsx

Update your wallet modal and recent transaction styling

feat(Dev-517): update your wallet styling

---

apps/web/src/components/Menu/config/config.ts

feat(DEV-520): add back nft menu item

---

.github/workflows/deploy-dev.yml
.github/workflows/test-branch.yml
apps/web/src/pages/nfts/collections/[collectionAddress].tsx
apps/web/src/pages/nfts/collections/[collectionAddress]/[tokenId].tsx
apps/web/src/state/nftMarket/helpers.ts
apps/web/src/views/Nft/market/ActivityHistory/utils/fetchActivityNftMetadata.tsx
apps/web/src/views/Nft/market/ActivityHistory/utils/sortActivity.tsx
apps/web/src/views/Nft/market/components/SearchBar.tsx
apps/web/src/views/Nft/market/hooks/useAllPancakeBunnyNfts.ts
apps/web/src/views/Nft/market/hooks/useCollectionNfts.tsx
apps/web/src/views/Nft/market/hooks/useGetCollectionDistribution.tsx

Re enable pipelines

---

packages/uikit/src/components/Spinner/Spinner.tsx

update spinner styles
https://user-images.githubusercontent.com/7094663/223196108-82bd1a55-1766-4654-bb68-e5bbade1feac.mov
https://user-images.githubusercontent.com/7094663/223196113-4f806204-fa4a-4f9e-ba31-069ebba1c755.mov

update spinner styles

---

apps/web/src/views/FarmAuction/components/PlaceBidModal.tsx
apps/web/src/views/FarmAuction/components/WhitelistedBiddersModal.tsx
apps/web/src/views/LimitOrders/components/ConfirmLimitOrderModal.tsx
apps/web/src/views/LimitOrders/components/LimitOrderTable/DetailLimitOrderModal.tsx
apps/web/src/views/Nft/market/Home/index.tsx
apps/web/src/views/Nft/market/components/Activity/MobileModal.tsx
apps/web/src/views/Nft/market/components/BuySellModals/BuyModal/index.tsx
apps/web/src/views/Nft/market/components/BuySellModals/SellModal/index.tsx
apps/web/src/views/Nft/market/components/ProfileNftModal.tsx
apps/web/src/views/Pools/components/LockedPool/Modals/AddAmountModal.tsx
apps/web/src/views/Pools/components/LockedPool/Modals/ExtendDurationModal.tsx
apps/web/src/views/Pools/components/LockedPool/Modals/LockedStakeModal.tsx
apps/web/src/views/Pools/components/Modals/NotEnoughTokensModal.tsx
apps/web/src/views/Pools/components/RebusVaultCard/VaultStakeModal.tsx
apps/web/src/views/Swap/components/SwapWarningModal/index.tsx
apps/web/src/views/TradingCompetition/components/TeamRanks/TeamRanksWithParticipants.tsx
packages/uikit/src/components/Card/index.stories.tsx
packages/uikit/src/components/Card/theme.ts
packages/uikit/src/widgets/Modal/NotEnoughTokensModal.tsx
packages/uikit/src/widgets/Modal/index.stories.tsx
packages/uikit/src/widgets/Pool/CollectModal.tsx
packages/uikit/src/widgets/Pool/StakeModal.tsx

replace the rest of the modal gradients, change .gradientCardHeader to .backgroundAlt

find and replace modal headers

---

apps/web/src/views/Farms/Farms.tsx
apps/web/src/views/Farms/components/FarmCard/CardActionsContainer.tsx
apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
apps/web/src/views/Farms/components/FarmTable/Row.tsx

remove yield booster ui and farm types filter

Dev 542 remove yield booster

---

apps/web/src/views/AddLiquidity/index.tsx
apps/web/src/views/Pool/index.tsx

Remove option to add custom liquidity token pair

DEV-559 Remove option to add custom liquidity token pair

---

apps/web/src/components/CurrencyInputPanel/index.tsx
apps/web/src/components/SearchModal/CurrencySearch.tsx
apps/web/src/components/SearchModal/CurrencySearchModal.tsx
apps/web/src/config/constants/tokenLists/vertotrade-default.tokenlist.json
apps/web/src/hooks/Tokens.ts
apps/web/src/hooks/Trades.ts
apps/web/src/state/swap/hooks.ts
apps/web/src/views/Swap/SmartSwap/index.tsx
apps/web/src/views/Swap/components/SwapForm.tsx
apps/web/src/views/Swap/hooks/useWarningImport.tsx
packages/swap-sdk-core/src/token.ts
packages/token-lists/src/types.ts
packages/token-lists/src/wrappedTokenInfo.ts

Disable swap of other assets besides rebus and wrebus

Disable swap of other assets besides rebus and wrebus

---

apps/web/src/config/abi/erc20.json
apps/web/src/config/constants/pools.tsx
apps/web/src/state/pools/fetchPools.ts
apps/web/src/state/pools/hooks.ts
apps/web/src/state/pools/index.ts
apps/web/src/views/Home/hooks/useGetTopPoolsByApr.tsx
apps/web/src/views/Pools/components/PoolStatsInfo.tsx
packages/localization/src/config/translations.json

This code adds the calls to the abi to retrieve the new properties from the pool contracts. It gets widthdrawFee, widthdrawFeePeriod, depositFee, userInfo, and is boosted. The UI integration of this information will be made in the following prs.

Dev 568 display minting pools in UI

---

apps/web/src/config/constants/pools.tsx
apps/web/src/state/pools/fetchPools.ts
apps/web/src/state/pools/hooks.ts
apps/web/src/state/pools/index.ts
apps/web/src/state/types.ts
apps/web/src/views/Pools/components/PoolStatsInfo.tsx
packages/localization/src/config/translations.json
packages/tokens/src/1111.ts
packages/uikit/src/widgets/Pool/types.ts

Add aureus pool and add withdrawl pool stats

DEV-568 Add aureus pool and add withdrawl pool stats

---

apps/web/src/views/Pools/components/PoolStatsInfo.tsx
packages/localization/src/config/translations.json
packages/uikit/src/widgets/Pool/types.ts

add deposit fee and isBoosted tag to the ui

Add deposit fee pool UI

---

.github/workflows/action-build.yml
.github/workflows/test-branch.yml

Removes unnecessary code that caused the test to fail.

fix failing test

---

apps/web/src/views/Pools/components/PoolStatsInfo.tsx

Fix for withdraw period bug, adjusted the logic and tested with the user's address.

bugfix(Dev-578): update withdraw fee period

---

apps/web/src/config/constants/pools.tsx
packages/tokens/src/1111.ts

Add ludus pool

---

apps/web/package.json
apps/web/public/locales/en-US.json
apps/web/src/config/abi/erc20.json
apps/web/src/config/constants/pools.tsx
apps/web/src/state/pools/fetchPools.ts
apps/web/src/state/pools/index.ts
apps/web/src/state/types.ts
apps/web/src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx
apps/web/src/views/Pools/components/PoolsTable/Cells/EndsInCell.tsx
apps/web/src/views/Pools/index.tsx
packages/uikit/src/widgets/Pool/PoolControls.tsx
packages/uikit/src/widgets/Pool/types.ts

- Add pools whitelist/boosted features

DEV-592 Add pools whitelist/boosted features

---

apps/web/src/views/Tokens/Cells/ActionCell.tsx
apps/web/src/views/Tokens/Cells/AddressCell.tsx
apps/web/src/views/Tokens/Cells/BalanceCell.tsx
apps/web/src/views/Tokens/Cells/NameCell.tsx
apps/web/src/views/Tokens/TokenRow.tsx
apps/web/src/views/Tokens/index.tsx
packages/tokens/src/3333.ts

- Address styling issues
- Add address column to tokens page
- Display tokens even when disconnected from wallet

DEV-595 Tokens Page Issues

---

apps/web/src/config/constants/pools.tsx

Add new mainnet xverto pool contract

Add new mainnet xverto pool contract

---

apps/web/src/views/Pools/components/PoolsTable/Cells/EndsInCell.tsx
apps/web/src/views/Pools/helpers.tsx

Fix block countdown for pools

---

apps/web/src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx

Fix stake button disabled for new pool

Fix stake button disabled for new pool

---

apis/farms/src/provider.ts
apps/web/src/utils/providers.ts
apps/web/src/utils/wagmi.ts

Update url used for rpc to separate it from the one used by the wallet

Update url used for rpc to separate it from the one used by the wallet

---

apis/farms/src/provider.ts
apps/web/src/utils/providers.ts
apps/web/src/utils/wagmi.ts

Update mainnet api url

---

apps/web/src/hooks/useAuth.tsx

Fix wrong api url being added to metamask

Fix wrong api url being added to metamask

---

apps/web/src/utils/wagmi.ts

Configure websocket url

---

apps/web/src/config/constants/pools.tsx
packages/uikit/src/widgets/Pool/PoolControls.tsx
packages/uikit/src/widgets/Pool/types.ts

Add xverto/verto pool and static config to show pool after block

Add xverto/verto pool and static config to show pool after block

---

apps/web/src/config/constants/pools.tsx

Add new xverto pool

---

apps/web/src/config/constants/pools.tsx

Add investor xverto-verto pool

Add investor xverto-verto pool

---

apps/web/public/locales/ar-SA.json
apps/web/public/locales/bn-BD.json
apps/web/public/locales/de-DE.json
apps/web/public/locales/el-GR.json
apps/web/public/locales/en-US.json
apps/web/public/locales/es-ES.json
apps/web/public/locales/fi-FI.json
apps/web/public/locales/fil-PH.json
apps/web/public/locales/fr-FR.json
apps/web/public/locales/hi-IN.json
apps/web/public/locales/hu-HU.json
apps/web/public/locales/id-ID.json
apps/web/public/locales/it-IT.json
apps/web/public/locales/ja-JP.json
apps/web/public/locales/ko-KR.json
apps/web/public/locales/nl-NL.json
apps/web/public/locales/pl-PL.json
apps/web/public/locales/pt-BR.json
apps/web/public/locales/pt-PT.json
apps/web/public/locales/ro-RO.json
apps/web/public/locales/ru-RU.json
apps/web/public/locales/sv-SE.json
apps/web/public/locales/ta-IN.json
apps/web/public/locales/tr-TR.json
apps/web/public/locales/uk-UA.json
apps/web/public/locales/vi-VN.json
apps/web/public/locales/zh-CN.json
apps/web/public/locales/zh-TW.json
apps/web/src/views/Home/components/SalesSection/data.ts
packages/localization/src/config/translations.json

feat(Dev-623): update copy on homepage

---

apps/web/src/views/Home/components/SalesSection/index.tsx
apps/web/src/views/Home/index.tsx

Add responsive style changes to the homepage

Homepage responsive styles

---

apps/web/src/config/constants/tokenLists/1111/vertotrade-default.tokenlist.json
packages/tokens/src/1111.ts

Fix decimals on axlUSDC coin

---

apps/web/src/components/PositionCard/index.tsx
apps/web/src/views/AddLiquidity/AddStableLiquidity/index.tsx
apps/web/src/views/AddLiquidity/index.tsx
apps/web/src/views/Pool/index.tsx
apps/web/src/views/RemoveLiquidity/RemoveStableLiquidity/index.tsx
apps/web/src/views/RemoveLiquidity/index.tsx
apps/web/src/views/Swap/SmartSwap/components/SwapModalHeader.tsx
apps/web/src/views/Swap/StableSwap/components/StableSwapModalHeader.tsx
apps/web/src/views/Swap/components/SwapModalHeader.tsx
packages/ui/tokens/colors.ts
packages/uikit/src/components/DropdownMenu/styles.tsx

Styling tweaks for the liquidity page

feat(Dev-603): liquidity-page-styling-tweaks

---

apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
packages/farms/constants/1111.ts

Add reward token to mainnet farm

Add reward token to mainnet farm

---

packages/uikit/src/components/Footer/Footer.tsx
packages/uikit/src/components/LangSelector/LangSelector.tsx
packages/uikit/src/components/ThemeSwitcher/ThemeSwitcher.tsx

update theme switcher and lang

---

apps/web/.env.development
apps/web/.env.production
apps/web/src/components/Menu/utils.ts

Update configuration for cms url

update cms url config

---

apps/web/.env.development
apps/web/.env.production

update vars prefix

---

apps/web/src/config/constants/tokenLists/1111/vertotrade-default.tokenlist.json

DEV-629 Fix axlUSDC on swap

---

apps/web/src/components/Menu/config/config.ts
apps/web/src/components/Menu/utils.ts
apps/web/src/views/Lottery/index.tsx

fix lottery flag issue

---

apps/web/.env
apps/web/.env.development
apps/web/.env.production
apps/web/src/state/farms/index.ts
apps/web/src/state/pools/fetchPools.ts
apps/web/src/state/pools/index.ts
apps/web/src/utils/apr.ts
apps/web/src/views/Farms/Farms.tsx
apps/web/src/views/Farms/components/FarmTable/Row.tsx
apps/web/src/views/Home/hooks/useGetTopFarmsByApr.tsx
apps/web/src/views/Migration/components/MigrationStep1/OldFarm/index.tsx
apps/web/src/views/Migration/components/MigrationStep2/NewFarm/index.tsx
apps/web/src/views/Pools/components/PoolsTable/Cells/EndsInCell.tsx
apps/web/src/views/Pools/components/PoolsTable/Cells/LiquidityCell.tsx
apps/web/src/views/Pools/components/PoolsTable/PoolHeaderRow.tsx
apps/web/src/views/Pools/components/PoolsTable/PoolRow.tsx
packages/farms/src/fetchFarms.ts
packages/uikit/src/widgets/Pool/types.ts
packages/uikit/src/widgets/Pool/withStakeActions.tsx

- Integrate APR and Liquidity for farms and pools

Feature/DEV-640 APR/Liquidity for Farms/Pools

---

apps/web/src/utils/apr.ts
apps/web/src/utils/fetchWithCache.ts
apps/web/src/utils/home.ts
apps/web/src/utils/prices.ts
apps/web/src/views/Farms/Farms.tsx
apps/web/src/views/Home/components/VertoDataRow.tsx

Home Page Data Integration

---

apps/web/public/locales/ar-SA.json
apps/web/public/locales/bn-BD.json
apps/web/public/locales/de-DE.json
apps/web/public/locales/el-GR.json
apps/web/public/locales/en-US.json
apps/web/public/locales/es-ES.json
apps/web/public/locales/fi-FI.json
apps/web/public/locales/fil-PH.json
apps/web/public/locales/fr-FR.json
apps/web/public/locales/hi-IN.json
apps/web/public/locales/hu-HU.json
apps/web/public/locales/id-ID.json
apps/web/public/locales/it-IT.json
apps/web/public/locales/ja-JP.json
apps/web/public/locales/ko-KR.json
apps/web/public/locales/nl-NL.json
apps/web/public/locales/pl-PL.json
apps/web/public/locales/pt-BR.json
apps/web/public/locales/pt-PT.json
apps/web/public/locales/ro-RO.json
apps/web/public/locales/ru-RU.json
apps/web/public/locales/sv-SE.json
apps/web/public/locales/ta-IN.json
apps/web/public/locales/tr-TR.json
apps/web/public/locales/uk-UA.json
apps/web/public/locales/vi-VN.json
apps/web/public/locales/zh-CN.json
apps/web/public/locales/zh-TW.json
apps/web/src/views/Home/components/VertoDataRow.tsx
packages/localization/src/config/translations.json

Fix home page emissions per block loading state

Fix home page emissions per block loading state

---

apps/web/src/pages/_app.tsx

Added version to hero png

---

.gitignore
apps/web/.env.production.local
apps/web/.gitignore
apps/web/package.json
apps/web/src/components/PairPriceDisplay.tsx
apps/web/src/views/Swap/SmartSwap/index.tsx
apps/web/src/views/Swap/components/CurrencyInputHeader.tsx
package.json
scripts/create-es-transform-transactions.ts
turbo.json

- Add mainnet config
- add command to run code locally for mainnet
- Remove chart button on swap page for wrebus-rebus pair

Mainnet Config for Deployment

---

apps/web/src/pages/_app.tsx
apps/web/src/state/swap/hooks.ts
apps/web/src/utils/fetchWithCache.ts
apps/web/src/views/Swap/components/Chart/BasicChart.tsx
apps/web/src/views/Swap/components/Chart/SwapLineChart.tsx
scripts/create-es-transform-transactions.ts

- Fix swap chart y axis and last price
- Fix es transform script
- Fix __ENV being cached by browser
- Fix sometimes cached data not being fetched instantly

Chart/APR/Price Data Fixes

---

apps/web/src/state/swap/hooks.ts

Fix last price shown on swap graph

Fix last price shown on swap graph

---

apps/web/src/components/Logo/DoubleLogo.tsx
apps/web/src/pages/liquidity.tsx
apps/web/src/pages/swap.tsx
apps/web/src/views/Swap/SmartSwap/index.tsx
apps/web/src/views/Swap/components/Chart/styles.tsx
apps/web/src/views/Swap/index.tsx

- Fix swap page chart on mobile
- Fix required network modal to show on swap and liquidity pages

Fix mobile chart

---

apps/web/src/state/swap/hooks.ts

- Fix calculation of price proportion for swap graph data

Fix calculation of price proportion for swap graph data

---

apps/web/src/config/constants/pools.tsx

Add xverto/techne pool

---

apps/web/src/utils/wagmi-chains.ts

DEV-698 Update wallet rpc url

---

packages/uikit/src/components/Footer/Footer.tsx
packages/uikit/src/components/LangSelector/LangSelector.tsx
packages/uikit/src/components/ThemeSwitcher/ThemeSwitcher.tsx

Left align navigation footer icons
Before: 
After:

left align navigation footer icons in footer section

---

apps/web/src/views/Info/components/ChartLoaders/BarChartLoaderSVG.tsx
apps/web/src/views/Info/components/ChartLoaders/CandleChartLoaderSVG.tsx
apps/web/src/views/Info/components/ChartLoaders/LineChartLoaderSVG.tsx

Changed colors for loader to follow branding

Updated settings for chart loaders

---

apps/web/src/components/Menu/UserMenu/WalletUserMenuItem.tsx
apps/web/src/components/Menu/UserMenu/index.tsx
packages/uikit/src/widgets/Menu/components/UserMenu/index.tsx
packages/uikit/src/widgets/Menu/components/UserMenu/styles.tsx

Update wallet dropdown menu
Before:
After:
https://github.com/vertotrade/verto.ui/assets/150782162/bbe59d67-38f0-4f1f-a725-dac5c7701158

update wallet dropdown menu icons and position

---

apps/web/src/views/Home/index.tsx

If the button do not fit in one line they should be move one below the other
Before:
After:

button placed one below other if not fit in one line

---

apps/web/src/views/Home/components/VertoDataRow.tsx
packages/uikit/src/components/Balance/Balance.tsx
packages/uikit/src/components/Text/Text.tsx

Updated the token details section
Updated the font-family to Poppins
Changed the color to 'text' black
Removed dividers
Placed information in 2 columns
Before
After

Updated the token details section

---

apps/web/src/views/Home/index.tsx

reset the height of Learn How To Start button to be the same with Connect Wallet button

resize Learn How To Start button

---

apps/web/src/state/nftMarket/helpers.ts
apps/web/src/state/nftMarket/hooks.ts
apps/web/src/state/nftMarket/storage.ts
apps/web/src/state/nftMarket/types.ts
apps/web/src/views/Nft/market/ActivityHistory/utils/fetchActivityNftMetadata.tsx
apps/web/src/views/Nft/market/Collection/Header.tsx
apps/web/src/views/Nft/market/Collection/IndividualNFTPage/shared/MoreFromThisCollection.tsx
apps/web/src/views/Nft/market/Collection/Items/CollectionNfts.tsx
apps/web/src/views/Nft/market/Collection/Items/Filters.tsx
apps/web/src/views/Nft/market/Collection/Items/SortSelect.tsx
apps/web/src/views/Nft/market/Collection/config.ts
apps/web/src/views/Nft/market/Collections/index.tsx
apps/web/src/views/Nft/market/components/BuySellModals/SellModal/SetPriceStage.tsx
apps/web/src/views/Nft/market/components/BuySellModals/SellModal/index.tsx
apps/web/src/views/Nft/market/components/CollectibleCard/CollectionCardWithVolume.tsx
apps/web/src/views/Nft/market/hooks/useCollectionNfts.tsx
apps/web/src/views/Nft/market/hooks/useGetCollectionDistribution.tsx
packages/uikit/src/components/Select/Select.tsx

- Add volume info on marketplace pages
- Add pagination/sorting on marketplace pages
- Fix clicking on filtered tokens in collection page
- Add verto as a default sell currency for marketplace tokens

Feature/DEV-696 NFT Marketplace Updates

---

apps/web/src/components/Menu/UserMenu/WalletModal.tsx

**Task**
[DEV-754](https://rebustoken.atlassian.net/browse/DEV-754?atlOrigin=eyJpIjoiNjlhMWFmZTI4ODkzNDNjMGE0ZTk1ZTI4ZjQxZTI0NmMiLCJwIjoiaiJ9)
**Description**
Fix the vertical jump when user switches between tabs in the wallet modal.
Before:
https://github.com/vertotrade/verto.ui/assets/14368843/1404e211-0d6e-43b4-9ea6-bfa54d611155
After:
https://github.com/vertotrade/verto.ui/assets/14368843/3f52071b-427f-4fd0-b4a8-bce3aaaa7fe2

DEV-754 Fix wallet modal vertical jump

---

apps/web/src/views/Nft/market/Home/Collections.tsx
apps/web/src/views/Nft/market/components/CollectibleCard/CollectionCard.tsx

Applied the new edits from design on Newest collection section and collection cards on Nft Collections page.
Dark Mode:
Light Mode:

newest collections section and collection cards

---

apps/web/src/components/Clip.tsx

added playsInline property to fix a bug on safari

---

packages/uikit/src/components/ButtonMenu/ButtonMenu.tsx
packages/uikit/src/components/ButtonMenu/ButtonMenuItem.tsx
packages/uikit/src/components/Footer/Footer.tsx
packages/uikit/src/components/MenuItem/styles.tsx
packages/uikit/src/components/ScrollToTopButton/ScrollToTopButtonV2.tsx
packages/uikit/src/components/Select/Select.tsx
packages/uikit/src/components/Spinner/Spinner.tsx
packages/uikit/src/components/Svg/Icons/SadSmilePlaceholder.tsx
packages/uikit/src/components/Table/Cell.tsx
packages/uikit/src/components/ToggleView/ToggleView.tsx

Modified the loader and ran prettier on the code

Fix loader and ran lint

---

apps/web/src/views/Nft/market/Home/config.tsx
apps/web/src/views/Nft/market/Home/index.tsx
apps/web/src/views/Nft/market/components/ApplyToMarketplace.tsx
apps/web/src/views/Nft/market/components/FAQs/FAQs.tsx
packages/uikit/src/components/Svg/Icons/MountainsImage.tsx
packages/uikit/src/components/Svg/index.tsx

Create "Apply to NFT" Marketplace component

DEV-760: Create Apply to NFT Marketplace component

---

apps/web/src/state/nftMarket/hooks.ts
apps/web/src/state/nftMarket/storage.ts

DEV-783: change default NFT Collection view to 'All'

---

apps/web/src/components/CurrencyInputPanel/index.tsx
apps/web/src/components/Menu/UserMenu/index.tsx
apps/web/src/config/constants/pools.tsx

- Integrate currency prices on currency input
- Removed invalid minting pool configs
- Fixed user account menu not working

DEV-798 Integrate currency prices on currency input

---

apis/farms/src/provider.ts
apps/web/.env
apps/web/.env.development
apps/web/src/hooks/Trades.ts
apps/web/src/utils/providers.ts
apps/web/src/utils/wagmi-chains.ts
apps/web/src/utils/wagmi.ts

Disable multi-hop swaps for wrapping and fix testnet urls

DEV-800 Disable multi-hop swaps for wrapping and fix testnet urls

---

apps/web/src/components/Logo/CurrencyLogo.tsx
apps/web/src/state/info/hooks.ts
apps/web/src/state/info/queries/helpers.ts
apps/web/src/state/info/queries/pools/poolData.ts
apps/web/src/state/info/queries/protocol/chart.ts
apps/web/src/state/info/queries/protocol/transactions.ts
apps/web/src/state/info/queries/tokens/chartData.ts
apps/web/src/state/info/queries/tokens/priceData.ts
apps/web/src/state/info/queries/tokens/tokenData.ts
apps/web/src/state/info/types.ts
apps/web/src/state/lists/hooks.ts
apps/web/src/state/swap/hooks.ts
apps/web/src/utils/elastic-search.ts
apps/web/src/utils/getTokenLogoURL.ts
apps/web/src/utils/prices.ts
apps/web/src/views/Info/Overview/index.tsx
apps/web/src/views/Info/Pools/PoolPage.tsx
apps/web/src/views/Info/Tokens/index.tsx
apps/web/src/views/Info/components/CurrencyLogo/index.tsx
apps/web/src/views/Info/components/InfoNav/index.tsx
apps/web/src/views/Info/components/InfoSearch/index.tsx
apps/web/src/views/Info/components/InfoTables/PoolsTable.tsx
apps/web/src/views/Info/components/InfoTables/TokensTable.tsx
apps/web/src/views/Info/components/InfoTables/TransactionsTable.tsx
apps/web/src/views/Info/components/TopTokenMovers/index.tsx
apps/web/src/views/Info/hooks/usePoolsData.ts
apps/web/src/views/Info/index.tsx
scripts/create-es-transform-transactions.ts

- Implemented correct data handling for info page and hide fields that we dont have yet
- Fix es transform for transactions

DEV-803 Info Page

---

apps/web/src/views/Tokens/Cells/AddressCell.tsx
apps/web/src/views/Tokens/Cells/NameCell.tsx
apps/web/src/views/Tokens/TokenRow.tsx
packages/tokens/src/1111.ts
packages/uikit/src/widgets/Pool/PoolsTable/ExpandRow.tsx

DEV-807 Fix tokens page

---

apps/web/src/views/RemoveLiquidity/index.tsx

DEV-810 Fix remove liquidity

---

apps/web/src/components/Menu/config/config.ts

feat/DEV-811 Add stats link to vertotrade navigation header

---

apps/web/src/views/Nft/market/components/BannerHeader/BannerImage.tsx

- fix(DEV-820): fix the ratio for hero image section
fix the ratio for hero image section
[JIRA-TICKET-DEV-820]

fix(DEV-820): fix the ratio for hero image section

---

apps/web/src/views/Nft/market/Home/config.tsx

- feat(DEV-825): update content on nft page
- **Hide** text under the headers (FAQ and Apply to NFT Marketplace!)
Update Lorem Ipsum from NFT Overview page 
[JIRA-TICKET-DEV-825](https://rebustoken.atlassian.net/browse/DEV-825?atlOrigin=eyJpIjoiYmNjYmVmZmNhNTA4NDZkMGE4ZTU5NTc1ZjVmNjkzODAiLCJwIjoiaiJ9)

feat(DEV-825): update content on nft page

---

apps/web/public/locales/ar-SA.json
apps/web/public/locales/bn-BD.json
apps/web/public/locales/de-DE.json
apps/web/public/locales/el-GR.json
apps/web/public/locales/en-US.json
apps/web/public/locales/es-ES.json
apps/web/public/locales/fi-FI.json
apps/web/public/locales/fil-PH.json
apps/web/public/locales/fr-FR.json
apps/web/public/locales/hi-IN.json
apps/web/public/locales/hu-HU.json
apps/web/public/locales/id-ID.json
apps/web/public/locales/it-IT.json
apps/web/public/locales/ja-JP.json
apps/web/public/locales/ko-KR.json
apps/web/public/locales/nl-NL.json
apps/web/public/locales/pl-PL.json
apps/web/public/locales/pt-BR.json
apps/web/public/locales/pt-PT.json
apps/web/public/locales/ro-RO.json
apps/web/public/locales/ru-RU.json
apps/web/public/locales/sv-SE.json
apps/web/public/locales/ta-IN.json
apps/web/public/locales/tr-TR.json
apps/web/public/locales/uk-UA.json
apps/web/public/locales/vi-VN.json
apps/web/public/locales/zh-CN.json
apps/web/public/locales/zh-TW.json
apps/web/src/views/Nft/market/components/BuySellModals/SellModal/SetPriceStage.tsx
packages/localization/src/config/translations.json

Description
Remove the maximum price or set it pretty high, something like 20M  tokens
Minimum we can use 1

DEV-824 Updates to the SetStagePrice Max and Min

---

packages/farms/constants/1111.ts

Fix lqVerto pool

---

apps/web/src/utils/wagmi-chains.ts

DEV-849 Update wallet mainnet config
