apps/web/src/components/FoldableSection/FoldableText.tsx
apps/web/src/components/FoldableSection/SectionsWithFoldableText.tsx
apps/web/src/views/Nft/market/Home/Collections.tsx
apps/web/src/views/Nft/market/Home/Newest.tsx
apps/web/src/views/Nft/market/Home/index.tsx
apps/web/src/views/Nft/market/components/CollectibleCard/CardBody.tsx
apps/web/src/views/Nft/market/components/CollectibleCard/CollectibleLinkCard.tsx
apps/web/src/views/Nft/market/components/CollectibleCard/CollectionCard.tsx
apps/web/src/views/Nft/market/components/CollectibleCard/PreviewImage.tsx
apps/web/src/views/Nft/market/components/CollectibleCard/styles.tsx
apps/web/src/views/Nft/market/components/NFTMedia.tsx
packages/localization/src/config/translations.json

Restyling the NFT overview page:

feat(DEV-521): restyle nft overview page

---

apps/web/src/pages/_app.tsx

This pull request adds the cache-control and expires meta tags to the <Head> section in order to prevent the browser from caching the source of the page.

add expires and no cache meta tags

---

apps/web/src/views/Home/index.tsx

If the button do not fit in one line they should be move one below the other
Before:
After:

button placed one below other if not fit in one line

---

packages/uikit/src/components/Footer/Footer.tsx

Remove hover color from all footer links
Before: 
After
https://github.com/vertotrade/verto.ui/assets/150782162/b0bd9675-b323-48a4-90b0-cd7d0f975c7c

remove hover color from all footer links

---

packages/uikit/src/components/ScrollToTopButton/ScrollToTopButtonV2.tsx

Remove scroll up button for mobile view
Before: 
After:

remove scroll up button for mobile view

---

apps/web/src/views/Home/components/VertoDataRow.tsx
packages/uikit/src/components/Balance/Balance.tsx
packages/uikit/src/components/Text/Text.tsx

Updated the token details section
- Updated the font-family to Poppins
- Changed the color to 'text' black
- Removed dividers
- Placed information in 2 columns

Updated the token details section

---

apps/web/src/views/Home/components/ColoredWordHeading.tsx
apps/web/src/views/Home/components/SalesSection/data.tsx
apps/web/src/views/Home/components/SalesSection/index.tsx

Resized the first heading in hero section.
Before:
After:

Resize the first heading in hero section

---

packages/uikit/src/components/DropdownMenu/styles.tsx

Update navigation dropdowns
Before:
After:
https://github.com/vertotrade/verto.ui/assets/150782162/764bd9d6-a54e-4301-bafa-ebbea5fc0c8d

update all the navigation dropdowns background and opacity

---

packages/uikit/src/components/Footer/Components/SocialLinks.tsx

Remove background color from social links
Before:
After
https://github.com/vertotrade/verto.ui/assets/150782162/3ef6e3a7-7ac0-4151-929d-3ce94911e120

remove background color from social links in footer section

---

apps/web/src/views/Home/components/SalesSection/index.tsx
apps/web/src/views/Home/index.tsx
packages/uikit/src/components/Link/Link.tsx
packages/uikit/src/components/Link/types.ts

Removed underlining for learn more buttons
Removed underlining for learn more buttons
Added hover effect to Learn more buttons
Before:
After:

Removed underlining for learn more buttons

---

apps/web/src/components/Clip.tsx
apps/web/src/components/IconDivider/index.tsx
apps/web/src/views/Home/components/SalesSection/data.tsx

Updated size of vcoin animation from 220x220 to 256x256.
Before:
After:
Note: height and width were set to 100% to its parent. Its parent element had the height and width set to 220px instead of 180px

Dev 721 updated size of vcoin animation

---

apps/web/src/views/Home/components/SalesSection/data.tsx
apps/web/src/views/Home/components/SalesSection/index.tsx
apps/web/src/views/Home/index.tsx
packages/uikit/src/components/Link/LinkExternal.tsx
packages/uikit/src/components/Link/types.ts

Removed icons from Learn More buttons.
A linting issue appeared in setupTests.js because of it file type I updated the file changing the file type to setupTests.ts.
PS: In order to stay consistent with UI I also removed the icon for Learn how to start button
Before:
After:

Dev 719 remove icon from learn more

---

apps/web/src/views/Home/index.tsx

**Task**
[DEV-744](https://rebustoken.atlassian.net/browse/DEV-744?atlOrigin=eyJpIjoiNTFhNmVmZDM2YjhhNGFkMWEzNTk1ZDlmZDVlZjExZGIiLCJwIjoiaiJ9)
**Description**
On small screens, the text on different sections in the home page should be left-aligned.
Before:
After:

DEV-744 Fix text-align on small screens

---

apps/web/src/components/Menu/UserMenu/WalletModal.tsx

**Task**
[DEV-740](https://rebustoken.atlassian.net/browse/DEV-740?atlOrigin=eyJpIjoiYjhhYjQ3YmMwMDkzNGM4MDhkMWMwNmQ0Y2ZlMGE2OGUiLCJwIjoiaiJ9)
**Description**
Removes the background color for both header and tabs section in the wallet modal
Before:
After:

DEV-740 Remove background color in header and tabs sections.

---

apps/web/src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/OwnerCard.tsx
apps/web/src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/index.tsx
apps/web/src/views/Nft/market/Collection/IndividualNFTPage/shared/DetailsCard.tsx
apps/web/src/views/Nft/market/Collection/IndividualNFTPage/shared/ExpandableCard.tsx
apps/web/src/views/Nft/market/Collection/IndividualNFTPage/shared/ManageNFTsCard.tsx
apps/web/src/views/Nft/market/Collection/IndividualNFTPage/shared/PropertiesCard.tsx
apps/web/src/views/Nft/market/Collection/IndividualNFTPage/shared/styles.tsx
apps/web/src/views/Nft/market/components/CollectibleCard/CollectionCard.tsx

Updated nft Details dropdown components UI due to [Figma](https://www.figma.com/file/kgG2H5rFVnvZjiPJ95Hq8G/Verto-trade?node-id=5110%3A5706&mode=dev):

DEV-776: Update nft Details dropdown component

---

apps/web/src/views/Nft/market/Collection/Items/CollectionWrapper.tsx
apps/web/src/views/Nft/market/components/CollectibleCard/CardBody.tsx
apps/web/src/views/Nft/market/components/CollectibleCard/styles.tsx
apps/web/src/views/Nft/market/components/NFTMedia.tsx

Updated /nfts Collection cards UI due to [Figma](https://www.figma.com/file/kgG2H5rFVnvZjiPJ95Hq8G/Verto-trade?node-id=5133%3A2358&mode=dev):
P.s.: The currency symbol is calculated in CurrencyLogo component, but I could not find an example in our test data to be able to show dollar symbol, like on the design.

DEV-770: Update /nfts Collection cards

---

packages/ui-wallets/src/WalletModal.tsx

Fixed "Learn how to connect" button padding:

DEV-782: Fix "Learn how to connect" button padding

---

apps/web/src/views/Nft/market/components/BuySellModals/BuyModal/index.tsx
apps/web/src/views/Nft/market/components/BuySellModals/shared/ApproveAndConfirmStage.tsx

DEV-779: fix loading spinner on checkout
DEV- 781: display gas price when buying NFT
Deprecated:
UPD (with new Spinner):

DEV-779, DEV- 781: fix loading spinner on checkout, display gas price

---

packages/uikit/src/widgets/Menu/components/UserMenu/index.tsx

feat/DEV-795 Change the color of the arrow color on Wallet drop down

---

apps/web/src/components/Menu/config/config.ts

This commit https://github.com/vertotrade/verto.ui/commit/d40417fcc1a4f57845f26da118088a12350cae08#diff-e0daeed87867fc4fc6b0b1a9c2d52c9bfbd175cd1822e100f43300c4046484ad was made months ago but wasn't merged into main until recently, so I added this change https://github.com/vertotrade/verto.ui/commit/6497b99a85bc3cdd47b19ae48c29e216800ddf6d not knowing it was already done so now we were having double info tab.

DEV-823 Showing 2 Info links on VertoTrade header
